services:
  zookeeper-server:
    image: zookeeper:3.8.3-jre-17
    restart: always
    hostname: server.zookeeper.com
    labels:
      org.opencontainers.image.authors: "linghengqian@outlook.com"
    ports:
      - "2181:2181"
  hive-server2:
    image: apache/hive:4.0.0
    hostname: server2.hive.com
    restart: always
    depends_on:
      zookeeper-server:
        condition: service_started
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_CUSTOM_CONF_DIR: /hive_custom_conf
    labels:
      org.opencontainers.image.authors: "linghengqian@outlook.com"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./src/test/resources/hive-custom-conf/hive-site.xml:/hive_custom_conf